### PR TITLE
:bug: Fix bug when the type of input is mardown

### LINKED ISSUE #26: :bug: bug when the parser tries to parse a markdown file
**🐛 Describe the bug**
When the parser receives any kind of markdown file, the parser sends an error and not creates a file

**👀 To Reproduce**
1. Launch the program with an input file of format Markdown
2. You would be seen an error

**🤷 Expected behavior**
When the program receives a markdown file as it input the program, should create an empty document
the parsing of Markdown can be added latter

**💻 Desktop (please complete the following information):**
 - OS: [Fedora 40]

### PR DESCRIPTION
**Pull request by 6im0n**
📋 Changes made
- fix the output of the program when the type of input is mardown

# :link:  Linked issue
- #26

### CODE REVIEW

**Review by axel-eck — APPROVED** [review]

File: src/Core.hs [hunk 1]
```diff
@@ -43,11 +43,13 @@ writeDocString (App (Options _ (Just "json") _ _) _)
     (Just doc) = Just (documentToJSON doc)
 writeDocString (App (Options _ (Just "markdown") _ _) _)
     (Just doc) = Just (writeMarkdownDocument doc)
+writeDocString (App (Options (Just "markdown") (Just _) _ _) _) _ = Just ""
 writeDocString _ _ = Nothing
 
 writeTheDoc :: IO ()
 writeTheDoc = do
     app <- getOption
+    print (getParserContent app)
```
Comment (Marius-P1) [inline src/Core.hs]: you need to remove this debug

**Review by Marius-P1 — APPROVED** [review]
:ok_hand:

**Review by landryarki — APPROVED** [review]
